# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True, verbose_name='工程名')),
                ('issue_content', models.CharField(max_length=500, null=True, verbose_name='发布内容')),
                ('issue_time', models.TimeField(null=True)),
                ('dev_person', models.CharField(max_length=100, null=True, verbose_name='开发人员')),
                ('test_person', models.CharField(max_length=100, null=True, verbose_name='测试人员')),
                ('issue_person', models.CharField(max_length=100, null=True, verbose_name='发布人员')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注信息')),
            ],
            options={
                'db_table': 'issue_issuerecord',
                'ordering': ['id'],
            },
        ),
    ]
