# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerecord',
            name='issue_status',
            field=models.BooleanField(default=False, verbose_name='发布状态'),
        ),
        migrations.AddField(
            model_name='issuerecord',
            name='svn_path',
            field=models.CharField(max_length=500, null=True, verbose_name='svn路径'),
        ),
    ]
