# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20170918_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerecord',
            name='project_name',
            field=models.CharField(max_length=100, verbose_name='工程名'),
        ),
    ]
