# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20170919_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerecord',
            name='issue_status',
            field=models.CharField(default='1', max_length=3, verbose_name='发布状态'),
        ),
    ]
