# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20170903_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=32, verbose_name='业务线的名字')),
                ('module_letter', models.CharField(db_index=True, max_length=10, verbose_name='业务线字母简称')),
                ('op_interface', models.CharField(max_length=150, verbose_name='运维对接人')),
                ('dev_interface', models.CharField(max_length=150, verbose_name='业务对接人')),
                ('pid', models.IntegerField(db_index=True, verbose_name='上级业务线id')),
            ],
            options={
                'db_table': 'resources_my_product',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.IntegerField(null=True, verbose_name='供应商')),
                ('manufacturers', models.CharField(max_length=50, null=True, verbose_name='生产厂商')),
                ('manufacture_date', models.DateField(null=True, verbose_name='生产日期')),
                ('server_type', models.CharField(max_length=20, null=True, verbose_name='服务器类型')),
                ('sn', models.CharField(db_index=True, max_length=60, null=True, verbose_name='SN码')),
                ('os', models.CharField(max_length=50, null=True, verbose_name='操作系统')),
                ('hostname', models.CharField(db_index=True, max_length=50, null=True, verbose_name='主机名')),
                ('inner_ip', models.CharField(max_length=32, null=True, unique=True, verbose_name='管理ip')),
                ('mac_address', models.CharField(max_length=50, null=True, verbose_name='mac地址')),
                ('ip_info', models.CharField(max_length=255, null=True, verbose_name='ip信息')),
                ('server_cpu', models.CharField(max_length=250, null=True, verbose_name='cpu信息')),
                ('server_disk', models.CharField(max_length=100, null=True, verbose_name='磁盘信息')),
                ('server_mem', models.CharField(max_length=100, null=True, verbose_name='内存信息')),
                ('status', models.CharField(db_index=True, max_length=100, null=True, verbose_name='服务器状态')),
                ('remark', models.TextField(null=True)),
                ('service_id', models.IntegerField(db_index=True, null=True)),
                ('server_purpose', models.IntegerField(db_index=True, null=True)),
                ('check_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('vm_status', models.IntegerField(db_index=True, null=True, verbose_name='虚拟机状态')),
                ('uuid', models.CharField(db_index=True, max_length=100, null=True, verbose_name='虚拟机uuid')),
                ('idc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Idc')),
            ],
            options={
                'db_table': 'resources_my_server',
                'ordering': ['id'],
            },
        ),
    ]
